import { Toaster } from "@/components/ui/sonner";
import { TanstackProvider } from "@/providers/tanstack-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const font = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense tracking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <TanstackProvider>
          {children}
          <Toaster position="bottom-left" />
        </TanstackProvider>
      </body>
    </html>
  );
}
